import "./globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import Image from "next/image";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="pt-BR">
      <body className={inter.className}>
        <header className="bg-black text-white">
          <div className="flex py-4 items-center container mx-auto">
            <div>
              <Image src="/logo.png" width={120} height={78} alt="Logo" />
            </div>

            <nav>
              <ul className="flex gap-4 font-semibold">
                <li>Home</li>
                <li>Sobre nós</li>
                <li>Atendimento</li>
                <li>Fale conosco</li>
              </ul>
            </nav>
          </div>
        </header>

        {children}

        <footer className="bg-black text-white">
          <div className="flex justify-between py-4 items-center container mx-auto">
            <div className="w-1/2">
              <Image src="/logo.png" width={200} height={130} alt="Logo" />
            </div>
            <div className="w-1/2">
              <div>Serviços</div>
              <ul className="flex flex-col gap-2 font-semibold mt-4">
                <li>Home</li>
                <li>Sobre nós</li>
                <li>Atendimento</li>
                <li>Fale conosco</li>
              </ul>
            </div>
          </div>
          <div className="h-px my-4 bg-gray-700 container mx-auto"></div>
          <div className="flex py-4 items-center justify-center container mx-auto">
            <p>
              2023 © Edge Design. Todos os direitos reservados. | Políticas de
              privacidade
            </p>
          </div>
        </footer>
      </body>
    </html>
  );
}
